// MCC codes for merchant category classification
export const MCC_CODES = [
  { code: '5411', description: 'Grocery Stores & Supermarkets' },
  { code: '5812', description: 'Restaurants & Eating Places' },
  { code: '5814', description: 'Fast Food Restaurants' },
  { code: '5912', description: 'Drug Stores & Pharmacies' },
  { code: '5311', description: 'Department Stores' },
  { code: '5541', description: 'Gas Stations' },
  { code: '4121', description: 'Taxi & Limousines' },
  { code: '4112', description: 'Passenger Railways' },
  { code: '3000', description: 'Airlines' },
  { code: '7011', description: 'Hotels & Motels' },
  { code: '4814', description: 'Telecommunication Services' },
  { code: '4899', description: 'Cable & Streaming Services' },
  { code: '5699', description: 'Apparel & Accessories' },
  { code: '5945', description: 'Hobby, Toy & Game Shops' },
  { code: '7832', description: 'Movie Theaters' },
  { code: '5732', description: 'Electronics & Appliances' },
  
  { code: '5422', description: 'Freezer and Locker Meat Provisioners' },
  { code: '5441', description: 'Candy, Nut and Confectionery Stores' },
  { code: '5451', description: 'Dairy Products Stores' },
  { code: '5462', description: 'Bakeries' },
  { code: '5499', description: 'Miscellaneous Food Stores–Convenience Stores, Markets, Specialty Stores' },
  { code: '5811', description: 'Caterers' },
  { code: '5813', description: 'Bars, Cocktail Lounges, Discotheques, Nightclubs and Taverns' },
  { code: '5921', description: 'Package Stores–Beer, Wine and Liquor' },
  
  { code: '4225', description: 'Public Warehousing–Farm Products, Refrigerated Goods, Household Goods Storage' },
  { code: '5021', description: 'Office and Commercial Furniture' },
  { code: '5039', description: 'Construction Materials Not Elsewhere Classified' },
  { code: '5044', description: 'Office, Photographic, Photocopy and Microfilm Equipment' },
  { code: '5045', description: 'Computers, Computer Peripheral Equipment, Software' },
  { code: '5046', description: 'Commercial Equipment Not Elsewhere Classified' },
  { code: '5065', description: 'Electrical Parts and Equipment' },
  { code: '5072', description: 'Hardware Equipment and Supplies' },
  { code: '5074', description: 'Plumbing and Heating Equipment' },
  { code: '5094', description: 'Precious Stones and Metals, Watches and Jewelry' },
  { code: '5111', description: 'Stationery, Office Supplies, Printing and Writing Paper' },
  { code: '5137', description: 'Men's, Women's and Children's Uniforms and Commercial Clothing' },
  { code: '5139', description: 'Commercial Footware' },
  { code: '5192', description: 'Books, Periodicals and Newspapers' },
  { code: '5193', description: 'Florists Supplies, Nursery Stock and Flowers' },
  { code: '5200', description: 'Home Supply Warehouse Stores' },
  { code: '5211', description: 'Building Materials, Lumber Stores' },
  { code: '5231', description: 'Glass, Paint, Wallpaper Stores' },
  { code: '5251', description: 'Hardware Stores' },
  { code: '5261', description: 'Lawn and Garden Supply Stores' },
  { code: '5262', description: 'Marketplaces' },
  { code: '5271', description: 'Mobile Home Dealers' },
  { code: '5300', description: 'Wholesale Clubs' },
  { code: '5309', description: 'Duty Free Stores' },
  { code: '5310', description: 'Discount Stores' },
  { code: '5331', description: 'Variety Stores' },
  { code: '5399', description: 'Miscellaneous General Merchandise Stores' },
  { code: '5531', description: 'Automobile Supply Stores Or Home Supply Stores' },
  { code: '5611', description: 'Men's and Boys' Clothing and Accessories Stores' },
  { code: '5621', description: 'Women's Ready to Wear Stores' },
  { code: '5631', description: 'Women's Accessory and Specialty Stores' },
  { code: '5641', description: 'Children's and Infants' Wear Stores' },
  { code: '5651', description: 'Family Clothing Stores' },
  { code: '5655', description: 'Sports Apparel, and Riding Apparel Stores' },
  { code: '5661', description: 'Shoe Stores' },
  { code: '5681', description: 'Furriers and Fur Shops' },
  { code: '5691', description: 'Men's and Women's Clothing Stores' },
  { code: '5697', description: 'Alterations, Mending, Seamstresses, Tailors' },
  { code: '5698', description: 'Wig and Toupee Shops' },
  { code: '5699', description: 'Accessory and Apparel Stores–Miscellaneous' },
  { code: '5712', description: 'Equipment, Furniture and Home Furnishings Stores' },
  { code: '5713', description: 'Floor Covering Stores' },
  { code: '5714', description: 'Drapery, Upholstery and Window Coverings Stores' },
  { code: '5718', description: 'Fireplace, Fireplace Screens and Accessories Stores' },
  { code: '5719', description: 'Miscellaneous House Furnishing Specialty Shops' },
  { code: '5722', description: 'Household Appliance Stores' },
  { code: '5732', description: 'Electronics Sales' },
  { code: '5733', description: 'Music Stores–Musical Instruments, Pianos and Sheet Music' },
  { code: '5734', description: 'Computer Software Stores' },
  { code: '5735', description: 'Record Shops' },
  { code: '5815', description: 'Digital Goods: Books, Movies, Music' },
  { code: '5816', description: 'Digital Goods: Games' },
  { code: '5817', description: 'Digital Goods: Applications (Excludes Games)' },
  { code: '5818', description: 'Digital Goods: Large Digital Goods Merchant' },
  { code: '5931', description: 'Second Hand Stores, Used Merchandise Stores' },
  { code: '5932', description: 'Antique Shops–Sales, Repairs and Restoration Services' },
  { code: '5933', description: 'Pawn Shops' },
  { code: '5937', description: 'Antique Reproduction Stores' },
  { code: '5940', description: 'Bicycle Shops–Sales and Service' },
  { code: '5941', description: 'Sporting Goods Stores' },
  { code: '5942', description: 'Book Stores' },
  { code: '5943', description: 'Office, School Supply and Stationery Stores' },
  { code: '5944', description: 'Clock, Jewelry, Watch and Silverware Stores' },
  { code: '5946', description: 'Camera and Photographic Supply Stores' },
  { code: '5947', description: 'Card, Gift, Novelty and Souvenir Shops' },
  { code: '5948', description: 'Leather Goods and Luggage Stores' },
  { code: '5949', description: 'Fabric, Needlework, Piece Goods and Sewing Stores' },
  { code: '5950', description: 'Crystal and Glassware Stores' },
  { code: '5963', description: 'Door-to-Door Sales' },
  { code: '5964', description: 'Direct Marketing–Catalog Merchants' },
  { code: '5970', description: 'Artist Supply Stores, Craft Shops' },
  { code: '5971', description: 'Art Dealers and Galleries' },
  { code: '5972', description: 'Stamp and Coin Stores–Philatelic and Numismatic Supplies' },
  { code: '5973', description: 'Religious Goods Stores' },
  { code: '5977', description: 'Cosmetic Stores' },
  { code: '5978', description: 'Typewriter Stores–Rentals, Sales, Service' },
  { code: '5992', description: 'Florists' },
  { code: '5993', description: 'Cigar Stores and Stands' },
  { code: '5994', description: 'News Dealers and Newsstands' },
  { code: '5995', description: 'Pet Shops, Pet Food and Supplies' },
  { code: '5996', description: 'Swimming Pools–Sales and Supplies' },
  { code: '5997', description: 'Electric Razor Stores–Sales and Service' },
  { code: '5998', description: 'Tent and Awning Shops' },
  { code: '5999', description: 'Miscellaneous and Specialty Retail Stores' },
  
  { code: '7230', description: 'Barber and Beauty Shops' },
  { code: '7251', description: 'Hat Cleaning Shops, Shoe Repair Shops, Shoe Shine Parlors' },
  { code: '7273', description: 'Funeral Service and Crematories' },
  { code: '7277', description: 'Dating Services' },
  { code: '7278', description: 'Tax Preparation Service' },
  { code: '7296', description: 'Debt, Marriage, Personal–Counseling Services' },
  { code: '7297', description: 'Buying/Shopping Clubs, Services' },
  { code: '7298', description: 'Health and Beauty Spas' },
  { code: '7299', description: 'Other Services–Not Elsewhere Classified' },
  { code: '7321', description: 'Consumer Credit Reporting Agencies' },
  { code: '7361', description: 'Employment Agencies and Temporary Help Services' },
  { code: '7379', description: 'Computer Maintenance, Repair And Services–Not Elsewhere Classified' },
  { code: '7392', description: 'Consulting, Management and Public Relations Services' },
  { code: '7622', description: 'Electronic Repair Shops' },
  { code: '7623', description: 'Air Conditioning and Refrigeration Repair Shops' },
  { code: '7629', description: 'Appliance Repair Shops, Electrical and Small' },
  { code: '7631', description: 'Clock, Jewelry and Watch Repair Shops' },
  { code: '7641', description: 'Furniture–Reupholstery, Repair and Refinishing' },
  { code: '7993', description: 'Video Amusement Game Supplies' },
  { code: '8351', description: 'Organizations, Political' },
  { code: '9751', description: 'UK Supermarkets, Electronic Hot File' },
];

