// MCC codes for merchant category classification
export const MCC_CODES = (() => {
  // Original list of codes
  const originalCodes = [
    {
      code: "1520",
      description: "General Contractors–Residential and Commercial",
    },
    { code: "5411", description: "Grocery Stores & Supermarkets" },
    { code: "5812", description: "Restaurants & Eating Places" },
    { code: "5814", description: "Fast Food Restaurants" },
    { code: "5912", description: "Drug Stores & Pharmacies" },
    { code: "5311", description: "Department Stores" },
    { code: "5541", description: "Gas Stations" },
    { code: "4121", description: "Taxi & Limousines" },
    { code: "4112", description: "Passenger Railways" },

    // Airlines (3000-3350 range) - Merchant-specific MCCs
    { code: "3000", description: "United Airlines" },
    { code: "3001", description: "American Airlines" },
    { code: "3002", description: "Pan American World Airways" },
    { code: "3003", description: "Eurofly" },
    { code: "3004", description: "Dragon Airlines" },
    { code: "3005", description: "British Airways" },
    { code: "3006", description: "Japan Airlines" },
    { code: "3007", description: "Air France" },
    { code: "3008", description: "Lufthansa" },
    { code: "3009", description: "Air Canada" },
    { code: "3010", description: "KLM Royal Dutch Airlines" },
    { code: "3011", description: "Aeroflot" },
    { code: "3012", description: "Qantas" },
    { code: "3013", description: "Alitalia" },
    { code: "3014", description: "Saudi Arabian Airlines" },
    { code: "3015", description: "Swiss International Air Lines" },
    { code: "3016", description: "SAS Scandinavian Airlines" },
    { code: "3017", description: "South African Airways" },
    { code: "3018", description: "Varig" },
    { code: "3020", description: "Air India" },
    { code: "3021", description: "Air Algerie" },
    { code: "3022", description: "Philippine Airlines" },
    { code: "3023", description: "Mexicana de Aviacion" },
    { code: "3024", description: "Pakistan International Airlines" },
    { code: "3025", description: "Air New Zealand" },
    { code: "3026", description: "Emirates" },
    { code: "3027", description: "UTA/Interair" },
    { code: "3028", description: "Air Malta" },
    { code: "3029", description: "Bangladesh Biman Airlines" },
    { code: "3030", description: "Aer Lingus" },
    { code: "3031", description: "VIASA" },
    { code: "3032", description: "Malaysia Airlines" },
    { code: "3033", description: "Czech Airlines" },
    { code: "3034", description: "Etihad Airways" },
    { code: "3035", description: "El Al" },
    { code: "3036", description: "AVIANCA" },
    { code: "3037", description: "LADECO" },
    { code: "3038", description: "LAB Airlines" },
    { code: "3039", description: "Finnair" },
    { code: "3040", description: "Gulf Air Bahrain" },
    { code: "3041", description: "Garuda Indonesia" },
    { code: "3042", description: "Braathens Airlines" },
    { code: "3043", description: "Saudia" },
    { code: "3044", description: "Air Lanka" },
    { code: "3045", description: "Aloha Airlines" },
    { code: "3046", description: "LANCHILE" },
    { code: "3047", description: "VASP" },
    { code: "3048", description: "TAP Air Portugal" },
    { code: "3049", description: "Bangladesh Airlines" },
    { code: "3050", description: "Pluna" },
    { code: "3051", description: "LACSA" },
    { code: "3052", description: "Ecuatoriana" },
    { code: "3053", description: "Austrian Airlines" },
    { code: "3054", description: "LAM Mozambique Airlines" },
    { code: "3055", description: "TACA International" },
    { code: "3056", description: "SAETA" },
    { code: "3057", description: "AVIACO" },
    { code: "3058", description: "Delta Air Lines" },
    { code: "3059", description: "Northwest Airlines" },
    { code: "3060", description: "Continental Airlines" },
    { code: "3061", description: "Trans World Airlines" },
    { code: "3062", description: "Viação Aérea Riograndense" },
    { code: "3063", description: "Middle East Airlines" },
    { code: "3064", description: "Olympic Airways" },
    { code: "3065", description: "Tiger Airways" },
    { code: "3066", description: "Air Inter" },
    { code: "3067", description: "Southwest Airlines" },
    { code: "3068", description: "Air Seychelles" },
    { code: "3069", description: "Air Panama" },
    { code: "3070", description: "Faucett Airlines" },
    { code: "3071", description: "Alyemda Airlines" },
    { code: "3072", description: "Syrian Arab Airlines" },
    { code: "3073", description: "Srilankan Airlines" },
    { code: "3074", description: "Icelandair" },
    { code: "3075", description: "Yemen Airways" },
    { code: "3076", description: "Caribbean Airlines" },
    { code: "3077", description: "Dominican Airlines" },
    { code: "3078", description: "Tarom" },
    { code: "3079", description: "Air Madagascar" },
    { code: "3080", description: "Air Zimbabwe" },
    { code: "3081", description: "Kenya Airways" },
    { code: "3082", description: "Korean Air" },
    { code: "3083", description: "ANA All Nippon Airways" },
    { code: "3084", description: "Cameroon Airlines" },
    { code: "3085", description: "COPA Panama" },
    { code: "3086", description: "Aerolineas Argentinas" },
    { code: "3087", description: "Jet Airways" },
    { code: "3088", description: "Air Vanuatu" },
    { code: "3089", description: "TAA Airlines" },
    { code: "3090", description: "China Eastern Airlines" },
    { code: "3091", description: "Egyptair" },
    { code: "3092", description: "China Southern Airlines" },
    { code: "3093", description: "Air China" },
    { code: "3094", description: "Zambia Airways" },
    { code: "3095", description: "Air Pacific" },
    { code: "3096", description: "Air Mauritius" },
    { code: "3097", description: "Cathay Pacific" },
    { code: "3098", description: "Iraqi Airways" },
    { code: "3099", description: "Ghana Airways" },
    { code: "3100", description: "Nigeria Airways" },
    { code: "3102", description: "LOT Polish Airlines" },
    { code: "3103", description: "Tunis Air" },
    { code: "3106", description: "Air Niugini" },
    { code: "3110", description: "ACES" },
    { code: "3111", description: "British Midland" },
    { code: "3112", description: "EVA Airways" },
    { code: "3115", description: "Royal Nepal Airlines" },
    { code: "3117", description: "Viasa" },
    { code: "3118", description: "Laker Airways" },
    { code: "3125", description: "TAM Linhas Aéreas" },
    { code: "3127", description: "Southwest Airlines" },
    { code: "3129", description: "SunCountry Airlines" },
    { code: "3130", description: "Frontier Airlines" },
    { code: "3131", description: "Spirit Airlines" },
    { code: "3132", description: "Virgin America" },
    { code: "3133", description: "Alaska Airlines" },
    { code: "3135", description: "Thai Airways" },
    { code: "3136", description: "Turkish Airlines" },
    { code: "3137", description: "Transavia Holland" },
    { code: "3138", description: "WestJet" },
    { code: "3141", description: "Air Jamaica" },
    { code: "3143", description: "Viva Aerobus" },
    { code: "3144", description: "Singapore Airlines" },
    { code: "3145", description: "Scoot" },
    { code: "3146", description: "Volaris" },
    { code: "3148", description: "JetBlue Airways" },
    { code: "3151", description: "Air Transat" },
    { code: "3156", description: "IndiGo Airlines" },
    { code: "3159", description: "SpiceJet" },
    { code: "3161", description: "VietJet Air" },
    { code: "3163", description: "Bamboo Airways" },
    { code: "3171", description: "Vietnam Airlines" },
    { code: "3174", description: "EVA Air" },
    { code: "3175", description: "Cebu Pacific" },
    { code: "3176", description: "AirAsia" },
    { code: "3177", description: "AirAsia X" },
    { code: "3180", description: "Jetstar" },
    { code: "3181", description: "Lion Air" },
    { code: "3182", description: "Batik Air" },
    { code: "3184", description: "Starlux Airlines" },
    { code: "3196", description: "Peach Aviation" },
    { code: "3200", description: "Interjet" },
    { code: "3211", description: "Norwegian Air Shuttle" },
    { code: "3212", description: "Hawaiian Airlines" },
    { code: "3215", description: "China Airlines" },
    { code: "3217", description: "Spring Airlines" },
    { code: "3220", description: "Hong Kong Express" },
    { code: "3222", description: "Greater Bay Airlines" },
    { code: "3230", description: "HK Express" },
    { code: "3246", description: "Virgin Atlantic" },
    { code: "3251", description: "Ryanair" },
    { code: "3252", description: "easyJet" },
    { code: "3253", description: "Wizz Air" },
    { code: "3254", description: "Pegasus Airlines" },
    { code: "3256", description: "Vueling" },
    { code: "3260", description: "Condor" },
    { code: "3261", description: "Eurowings" },
    { code: "3266", description: "Air Serbia" },
    { code: "3267", description: "Iberia" },
    { code: "3280", description: "Alaska Airlines" },
    { code: "3282", description: "Air Baltic" },
    { code: "3285", description: "Azul Brazilian Airlines" },
    { code: "3292", description: "Sichuan Airlines" },
    { code: "3295", description: "Hainan Airlines" },
    { code: "3298", description: "Xiamen Airlines" },
    { code: "3299", description: "Air Macau" },
    { code: "4511", description: "Airlines - Not Elsewhere Classified" },

    // Hotels & Lodging (3501-3999 range) - Merchant-specific MCCs
    { code: "3501", description: "Holiday Inn" },
    { code: "3502", description: "Best Western" },
    { code: "3503", description: "Sheraton" },
    { code: "3504", description: "Hilton" },
    { code: "3505", description: "Trusthouse Forte" },
    { code: "3506", description: "Golden Tulip" },
    { code: "3507", description: "Friendship Inns" },
    { code: "3508", description: "Quality Inn" },
    { code: "3509", description: "Marriott" },
    { code: "3510", description: "Days Inn" },
    { code: "3511", description: "Arabella Hotels" },
    { code: "3512", description: "InterContinental" },
    { code: "3513", description: "Westin" },
    { code: "3514", description: "AmeriSuites" },
    { code: "3515", description: "Rodeway Inn" },
    { code: "3516", description: "La Quinta" },
    { code: "3517", description: "Americana Hotels" },
    { code: "3518", description: "Sol Hotels" },
    { code: "3519", description: "Pullman Hotels" },
    { code: "3520", description: "Meridien" },
    { code: "3521", description: "Crest Hotels" },
    { code: "3522", description: "Tokyo Hotel" },
    { code: "3523", description: "Peninsula Hotels" },
    { code: "3524", description: "Welcomgroup" },
    { code: "3525", description: "Dunfey Hotels" },
    { code: "3526", description: "Prince Hotels" },
    { code: "3527", description: "DoubleTree" },
    { code: "3528", description: "Red Lion Hotels" },
    { code: "3529", description: "CP Hotels" },
    { code: "3530", description: "Renaissance Hotels" },
    { code: "3531", description: "Kempinski Hotels" },
    { code: "3532", description: "ANA Hotels" },
    { code: "3533", description: "Jolly Hotels" },
    { code: "3534", description: "ITC Hotels" },
    { code: "3535", description: "Hilton International" },
    { code: "3536", description: "Mövenpick Hotels" },
    { code: "3537", description: "Scandic Hotels" },
    { code: "3538", description: "Doral Hotels" },
    { code: "3539", description: "Inn of the Sixth Mountain" },
    { code: "3540", description: "Leading Hotels of the World" },
    { code: "3541", description: "Ibis Hotels" },
    { code: "3542", description: "Hyatt" },
    { code: "3543", description: "Crown Hotels" },
    { code: "3544", description: "Shangri-La Hotels" },
    { code: "3545", description: "Grosvenor Hotels" },
    { code: "3546", description: "Sofitel" },
    { code: "3547", description: "Thistle Hotels" },
    { code: "3548", description: "Radisson SAS" },
    { code: "3549", description: "Park Lane Hotels" },
    { code: "3550", description: "Movenpick Hotels" },
    { code: "3551", description: "Langham Hotels" },
    { code: "3552", description: "Swissôtel" },
    { code: "3553", description: "Vista Hotels" },
    { code: "3554", description: "Ascott Serviced Residences" },
    { code: "3555", description: "Hoshino Resorts" },
    { code: "3556", description: "Marco Polo Hotels" },
    { code: "3557", description: "Shilla Hotels" },
    { code: "3558", description: "Radisson" },
    { code: "3559", description: "Nikko Hotels" },
    { code: "3560", description: "Okura Hotels" },
    { code: "3561", description: "Mandarin Oriental" },
    { code: "3562", description: "Comfort Inn" },
    { code: "3563", description: "Clarion Hotels" },
    { code: "3564", description: "Sleep Inn" },
    { code: "3565", description: "MainStay Suites" },
    { code: "3566", description: "Hampton Inn" },
    { code: "3567", description: "Ritz-Carlton" },
    { code: "3568", description: "Taj Hotels" },
    { code: "3569", description: "Oberoi Hotels" },
    { code: "3570", description: "Trident Hotels" },
    { code: "3571", description: "Park Hyatt" },
    { code: "3572", description: "Grand Hyatt" },
    { code: "3573", description: "Andaz" },
    { code: "3574", description: "Fairmont" },
    { code: "3575", description: "Raffles" },
    { code: "3576", description: "Swissotel" },
    { code: "3577", description: "Dusit Hotels" },
    { code: "3578", description: "Aman Resorts" },
    { code: "3579", description: "Six Senses" },
    { code: "3580", description: "Anantara" },
    { code: "3581", description: "Capella Hotels" },
    { code: "3582", description: "Como Hotels" },
    { code: "3583", description: "Rosewood Hotels" },
    { code: "3584", description: "Edition Hotels" },
    { code: "3585", description: "Melia Hotels" },
    { code: "3586", description: "Novotel" },
    { code: "3587", description: "Mercure Hotels" },
    { code: "3588", description: "Banyan Tree" },
    { code: "3589", description: "One&Only Resorts" },
    { code: "3590", description: "Four Seasons" },
    { code: "3591", description: "Mandarin Hotel Group" },
    { code: "3592", description: "Pan Pacific Hotels" },
    { code: "3593", description: "Parkroyal Hotels" },
    { code: "3594", description: "Regent Hotels" },
    { code: "3595", description: "Mandarin Oriental" },
    { code: "3596", description: "JW Marriott" },
    { code: "3597", description: "W Hotels" },
    { code: "3598", description: "Le Méridien" },
    { code: "3599", description: "W Hotels" },
    { code: "3600", description: "St. Regis" },
    { code: "3601", description: "Luxury Collection" },
    { code: "3602", description: "Tribute Portfolio" },
    { code: "3603", description: "Design Hotels" },
    { code: "3604", description: "Autograph Collection" },
    { code: "3605", description: "Delta Hotels" },
    { code: "3606", description: "AC Hotels" },
    { code: "3607", description: "Aloft Hotels" },
    { code: "3608", description: "Element Hotels" },
    { code: "3609", description: "Four Points" },
    { code: "3610", description: "Protea Hotels" },
    { code: "3611", description: "Moxy Hotels" },
    { code: "3612", description: "City Express" },
    { code: "3613", description: "Courtyard by Marriott" },
    { code: "3614", description: "Fairfield by Marriott" },
    { code: "3615", description: "Shangri-La" },
    { code: "3616", description: "Kerry Hotels" },
    { code: "3617", description: "Jen by Shangri-La" },
    { code: "3618", description: "Conrad Hotels" },
    { code: "3619", description: "Curio Collection" },
    { code: "3620", description: "Canopy by Hilton" },
    { code: "3621", description: "Tapestry Collection" },
    { code: "3622", description: "Embassy Suites" },
    { code: "3623", description: "Fairfield Inn" },
    { code: "3624", description: "Home2 Suites" },
    { code: "3625", description: "Homewood Suites" },
    { code: "3626", description: "Tru by Hilton" },
    { code: "3627", description: "Waldorf Astoria" },
    { code: "3628", description: "LXR Hotels" },
    { code: "3629", description: "Signia by Hilton" },
    { code: "3630", description: "Tempo by Hilton" },
    { code: "3631", description: "Renaissance" },
    { code: "3632", description: "SpringHill Suites" },
    { code: "3633", description: "TownePlace Suites" },
    { code: "3634", description: "Residence Inn" },
    { code: "3635", description: "Gaylord Hotels" },
    { code: "3636", description: "Bulgari Hotels" },
    { code: "3637", description: "St. Regis" },
    { code: "3638", description: "EDITION" },
    { code: "3639", description: "Ritz-Carlton Reserve" },
    { code: "3640", description: "Courtyard" },
    { code: "3641", description: "Hyatt Regency" },
    { code: "3642", description: "Hyatt Place" },
    { code: "3643", description: "Hyatt House" },
    { code: "3644", description: "Hyatt Centric" },
    { code: "3645", description: "The Unbound Collection" },
    { code: "3646", description: "Destination Hotels" },
    { code: "3647", description: "Thompson Hotels" },
    { code: "3648", description: "JdV by Hyatt" },
    { code: "3649", description: "Residence Inn" },
    { code: "3650", description: "Caption by Hyatt" },
    { code: "3651", description: "UrCove" },
    { code: "3652", description: "Miraval" },
    { code: "3653", description: "Exhale" },
    { code: "3654", description: "Accor Hotels" },
    { code: "3655", description: "Fairmont Hotels" },
    { code: "3656", description: "MGallery" },
    { code: "3657", description: "Mama Shelter" },
    { code: "3658", description: "25hours Hotels" },
    { code: "3659", description: "SLS Hotels" },
    { code: "3660", description: "Mondrian" },
    { code: "3661", description: "Delano" },
    { code: "3662", description: "Hyde Hotels" },
    { code: "3663", description: "Mantis Hotels" },
    { code: "3664", description: "Peppers Hotels" },
    { code: "3665", description: "Art Series Hotels" },
    { code: "3666", description: "Tribe Hotels" },
    { code: "3667", description: "BreakFree Hotels" },
    { code: "3668", description: "Mantra Hotels" },
    { code: "3669", description: "Adina Apartment Hotels" },
    { code: "3670", description: "Vibe Hotels" },
    { code: "3671", description: "Grand Millennium" },
    { code: "3672", description: "Millennium Hotels" },
    { code: "3673", description: "Copthorne Hotels" },
    { code: "3674", description: "M Social" },
    { code: "3675", description: "Studio M" },
    { code: "3676", description: "Lotte Hotels" },
    { code: "3677", description: "Signiel Hotels" },
    { code: "3678", description: "L7 Hotels" },
    { code: "3679", description: "Village Hotels" },
    { code: "3680", description: "Far East Hotels" },
    { code: "3681", description: "Oasia Hotels" },
    { code: "3682", description: "Quincy Hotels" },
    { code: "3683", description: "The Outpost Hotel" },
    { code: "3684", description: "Village Hotel" },
    { code: "3685", description: "Yotel" },
    { code: "3686", description: "citizenM" },
    { code: "3687", description: "Generator Hostels" },
    { code: "3688", description: "Selina Hotels" },
    { code: "3689", description: "Freehand Hotels" },
    { code: "3690", description: "Graduate Hotels" },
    { code: "3691", description: "Kimpton" },
    { code: "3692", description: "Hotel Indigo" },
    { code: "3693", description: "Crowne Plaza" },
    { code: "3694", description: "Holiday Inn Express" },
    { code: "3695", description: "Staybridge Suites" },
    { code: "3696", description: "Candlewood Suites" },
    { code: "3697", description: "Even Hotels" },
    { code: "3698", description: "Avid Hotels" },
    { code: "3699", description: "Voco Hotels" },
    { code: "7011", description: "Hotels & Motels - Not Elsewhere Classified" },
    { code: "7012", description: "Timeshares" },

    { code: "4814", description: "Telecommunication Services" },
    { code: "4816", description: "Computer Network/Information Services" },
    { code: "4899", description: "Cable & Streaming Services" },
    { code: "5699", description: "Apparel & Accessories" },
    { code: "5945", description: "Hobby, Toy & Game Shops" },
    { code: "7832", description: "Movie Theaters" },
    { code: "5732", description: "Electronics & Appliances" },

    { code: "5422", description: "Freezer and Locker Meat Provisioners" },
    { code: "5441", description: "Candy, Nut and Confectionery Stores" },
    { code: "5451", description: "Dairy Products Stores" },
    { code: "5462", description: "Bakeries" },
    {
      code: "5499",
      description:
        "Miscellaneous Food Stores–Convenience Stores, Markets, Specialty Stores",
    },
    { code: "5811", description: "Caterers" },
    {
      code: "5813",
      description:
        "Bars, Cocktail Lounges, Discotheques, Nightclubs and Taverns",
    },
    { code: "5921", description: "Package Stores–Beer, Wine and Liquor" },

    {
      code: "4225",
      description:
        "Public Warehousing–Farm Products, Refrigerated Goods, Household Goods Storage",
    },
    { code: "5021", description: "Office and Commercial Furniture" },
    {
      code: "5039",
      description: "Construction Materials Not Elsewhere Classified",
    },
    {
      code: "5044",
      description: "Office, Photographic, Photocopy and Microfilm Equipment",
    },
    {
      code: "5045",
      description: "Computers, Computer Peripheral Equipment, Software",
    },
    {
      code: "5046",
      description: "Commercial Equipment Not Elsewhere Classified",
    },
    { code: "5065", description: "Electrical Parts and Equipment" },
    { code: "5072", description: "Hardware Equipment and Supplies" },
    { code: "5074", description: "Plumbing and Heating Equipment" },
    {
      code: "5094",
      description: "Precious Stones and Metals, Watches and Jewelry",
    },
    {
      code: "5111",
      description: "Stationery, Office Supplies, Printing and Writing Paper",
    },
    {
      code: "5137",
      description:
        "Men's, Women's and Children's Uniforms and Commercial Clothing",
    },
    { code: "5139", description: "Commercial Footware" },
    { code: "5192", description: "Books, Periodicals and Newspapers" },
    {
      code: "5193",
      description: "Florists Supplies, Nursery Stock and Flowers",
    },
    { code: "5200", description: "Home Supply Warehouse Stores" },
    { code: "5211", description: "Building Materials, Lumber Stores" },
    { code: "5231", description: "Glass, Paint, Wallpaper Stores" },
    { code: "5251", description: "Hardware Stores" },
    { code: "5261", description: "Lawn and Garden Supply Stores" },
    { code: "5262", description: "Marketplaces" },
    { code: "5271", description: "Mobile Home Dealers" },
    { code: "5300", description: "Wholesale Clubs" },
    { code: "5309", description: "Duty Free Stores" },
    { code: "5310", description: "Discount Stores" },
    { code: "5331", description: "Variety Stores" },
    { code: "5399", description: "Miscellaneous General Merchandise Stores" },
    {
      code: "5531",
      description: "Automobile Supply Stores Or Home Supply Stores",
    },
    {
      code: "5611",
      description: "Men's and Boys' Clothing and Accessories Stores",
    },
    { code: "5621", description: "Women's Ready to Wear Stores" },
    { code: "5631", description: "Women's Accessory and Specialty Stores" },
    { code: "5641", description: "Children's and Infants' Wear Stores" },
    { code: "5651", description: "Family Clothing Stores" },
    { code: "5655", description: "Sports Apparel, and Riding Apparel Stores" },
    { code: "5661", description: "Shoe Stores" },
    { code: "5681", description: "Furriers and Fur Shops" },
    { code: "5691", description: "Men's and Women's Clothing Stores" },
    {
      code: "5697",
      description: "Alterations, Mending, Seamstresses, Tailors",
    },
    { code: "5698", description: "Wig and Toupee Shops" },
    { code: "5699", description: "Accessory and Apparel Stores–Miscellaneous" },
    {
      code: "5712",
      description: "Equipment, Furniture and Home Furnishings Stores",
    },
    { code: "5713", description: "Floor Covering Stores" },
    {
      code: "5714",
      description: "Drapery, Upholstery and Window Coverings Stores",
    },
    {
      code: "5718",
      description: "Fireplace, Fireplace Screens and Accessories Stores",
    },
    {
      code: "5719",
      description: "Miscellaneous House Furnishing Specialty Shops",
    },
    { code: "5722", description: "Household Appliance Stores" },
    { code: "5732", description: "Electronics Sales" },
    {
      code: "5733",
      description: "Music Stores–Musical Instruments, Pianos and Sheet Music",
    },
    { code: "5734", description: "Computer Software Stores" },
    { code: "5735", description: "Record Shops" },
    { code: "5815", description: "Digital Goods: Books, Movies, Music" },
    { code: "5816", description: "Digital Goods: Games" },
    {
      code: "5817",
      description: "Digital Goods: Applications (Excludes Games)",
    },
    {
      code: "5818",
      description: "Digital Goods: Large Digital Goods Merchant",
    },
    {
      code: "5931",
      description: "Second Hand Stores, Used Merchandise Stores",
    },
    {
      code: "5932",
      description: "Antique Shops–Sales, Repairs and Restoration Services",
    },
    { code: "5933", description: "Pawn Shops" },
    { code: "5937", description: "Antique Reproduction Stores" },
    { code: "5940", description: "Bicycle Shops–Sales and Service" },
    { code: "5941", description: "Sporting Goods Stores" },
    { code: "5942", description: "Book Stores" },
    {
      code: "5943",
      description: "Office, School Supply and Stationery Stores",
    },
    {
      code: "5944",
      description: "Clock, Jewelry, Watch and Silverware Stores",
    },
    { code: "5946", description: "Camera and Photographic Supply Stores" },
    { code: "5947", description: "Card, Gift, Novelty and Souvenir Shops" },
    { code: "5948", description: "Leather Goods and Luggage Stores" },
    {
      code: "5949",
      description: "Fabric, Needlework, Piece Goods and Sewing Stores",
    },
    { code: "5950", description: "Crystal and Glassware Stores" },
    { code: "5963", description: "Door-to-Door Sales" },
    { code: "5964", description: "Direct Marketing–Catalog Merchants" },
    {
      code: "5965",
      description: "Direct Marketing–Combination Catalog and Retail Merchant",
    },
    {
      code: "5966",
      description: "Direct Marketing–Outbound Telemarketing Merchants",
    },
    {
      code: "5967",
      description: "Direct Marketing–Inbound Telemarketing Merchants",
    },
    {
      code: "5968",
      description: "Direct Marketing–Continuity/Subscription Merchants",
    },
    {
      code: "5969",
      description:
        "Direct Marketing–Other Direct Marketers–Not Elsewhere Classified",
    },
    { code: "5970", description: "Artist Supply Stores, Craft Shops" },
    { code: "5971", description: "Art Dealers and Galleries" },
    {
      code: "5972",
      description: "Stamp and Coin Stores–Philatelic and Numismatic Supplies",
    },
    { code: "5973", description: "Religious Goods Stores" },
    { code: "5977", description: "Cosmetic Stores" },
    { code: "5978", description: "Typewriter Stores–Rentals, Sales, Service" },
    { code: "5992", description: "Florists" },
    { code: "5993", description: "Cigar Stores and Stands" },
    { code: "5994", description: "News Dealers and Newsstands" },
    { code: "5995", description: "Pet Shops, Pet Food and Supplies" },
    { code: "5996", description: "Swimming Pools–Sales and Supplies" },
    { code: "5997", description: "Electric Razor Stores–Sales and Service" },
    { code: "5998", description: "Tent and Awning Shops" },
    { code: "5999", description: "Miscellaneous and Specialty Retail Stores" },
    { code: "6513", description: "Real Estate Agents and Managers–Rentals" },

    { code: "7230", description: "Barber and Beauty Shops" },
    {
      code: "7251",
      description: "Hat Cleaning Shops, Shoe Repair Shops, Shoe Shine Parlors",
    },
    { code: "7273", description: "Funeral Service and Crematories" },
    { code: "7277", description: "Dating Services" },
    { code: "7278", description: "Tax Preparation Service" },
    {
      code: "7296",
      description: "Debt, Marriage, Personal–Counseling Services",
    },
    { code: "7297", description: "Buying/Shopping Clubs, Services" },
    { code: "7298", description: "Health and Beauty Spas" },
    { code: "7299", description: "Other Services–Not Elsewhere Classified" },
    { code: "7321", description: "Consumer Credit Reporting Agencies" },
    {
      code: "7361",
      description: "Employment Agencies and Temporary Help Services",
    },
    {
      code: "7379",
      description:
        "Computer Maintenance, Repair And Services–Not Elsewhere Classified",
    },
    {
      code: "7392",
      description: "Consulting, Management and Public Relations Services",
    },
    { code: "7622", description: "Electronic Repair Shops" },
    {
      code: "7623",
      description: "Air Conditioning and Refrigeration Repair Shops",
    },
    {
      code: "7629",
      description: "Appliance Repair Shops, Electrical and Small",
    },
    { code: "7631", description: "Clock, Jewelry and Watch Repair Shops" },
    {
      code: "7641",
      description: "Furniture–Reupholstery, Repair and Refinishing",
    },
    { code: "7993", description: "Video Amusement Game Supplies" },
    {
      code: "7997",
      description:
        "Clubs–Country Clubs, Membership (Athletic, Recreation, Sports), Private Golf Courses",
    },
    { code: "8351", description: "Organizations, Political" },
    { code: "9751", description: "UK Supermarkets, Electronic Hot File" },

    // Educational
    { code: "8211", description: "Elementary and Secondary Schools" },
    { code: "8220", description: "Colleges, Universities" },
    { code: "8241", description: "Correspondence Schools" },
    { code: "8244", description: "Business and Secretarial Schools" },
    { code: "8249", description: "Vocational and Trade Schools" },
    { code: "8299", description: "Schools and Educational Services" },

    // Government Services
    {
      code: "9211",
      description: "Court Costs, Including Alimony and Child Support",
    },
    { code: "9222", description: "Fines, Government Administrative Entities" },
    { code: "9223", description: "Bail and Bond Payments" },
    { code: "9311", description: "Tax Payments, Government Agencies" },
    { code: "9399", description: "Government Services" },
    { code: "9402", description: "Postal Services" },

    // Financial Services
    {
      code: "6010",
      description: "Financial Institutions - Manual Cash Disbursements",
    },
    {
      code: "6011",
      description: "Financial Institutions - Automated Cash Disbursements",
    },
    {
      code: "6012",
      description: "Financial Institutions - Merchandise and Services",
    },
    {
      code: "6051",
      description:
        "Non-Financial Institutions - Foreign Currency, Money Orders",
    },
    { code: "6211", description: "Securities Brokers/Dealers" },
    {
      code: "6300",
      description: "Insurance Sales, Underwriting, and Premiums",
    },
    {
      code: "6540",
      description:
        "POI (Point of Interaction) Funding Transactions (Excluding MoneySend)",
    },

    // Charitable & Social Service
    {
      code: "8398",
      description: "Charitable and Social Service Organizations",
    },
    { code: "8641", description: "Civic, Social, and Fraternal Associations" },
    { code: "8651", description: "Political Organizations" },
    { code: "8661", description: "Religious Organizations" },

    // Medical & Healthcare
    { code: "4119", description: "Ambulance Services" },
    {
      code: "5122",
      description: "Drugs, Drug Proprietaries, and Druggist Sundries",
    },
    { code: "5975", description: "Hearing Aids Sales, Service, and Supplies" },
    { code: "5976", description: "Orthopedic Goods - Prosthetic Devices" },
    {
      code: "7339",
      description: "Stenographic and Secretarial Support Services",
    },
    { code: "8011", description: "Doctors and Physicians" },
    { code: "8021", description: "Dentists and Orthodontists" },
    { code: "8031", description: "Osteopaths" },
    { code: "8041", description: "Chiropractors" },
    { code: "8042", description: "Optometrists and Ophthalmologists" },
    { code: "8043", description: "Opticians, Optical Goods, and Eyeglasses" },
    { code: "8049", description: "Podiatrists and Chiropodists" },
    { code: "8050", description: "Nursing and Personal Care Facilities" },
    { code: "8062", description: "Hospitals" },
    { code: "8071", description: "Medical and Dental Laboratories" },
    { code: "8099", description: "Medical Services and Health Practitioners" },
  ];

  // Create a Map to track unique codes
  const uniqueCodesMap = new Map();

  // Filter out duplicates by keeping only the first occurrence of each code
  originalCodes.forEach((mcc) => {
    if (!uniqueCodesMap.has(mcc.code)) {
      uniqueCodesMap.set(mcc.code, mcc);
    }
  });

  // Convert the Map values back to an array
  const uniqueCodes = Array.from(uniqueCodesMap.values());

  // Sort by code in ascending order
  return uniqueCodes.sort((a, b) => a.code.localeCompare(b.code));
})();
