
import { PaymentMethod } from '@/types';

// Default payment methods
export const defaultPaymentMethods: PaymentMethod[] = [
  // Cash options for different currencies
  {
    id: '1',
    name: 'Cash (USD)',
    type: 'cash',
    currency: 'USD',
    rewardRules: [],
    active: true,
    icon: 'banknote',
    color: '#22c55e',
  },
  {
    id: '1-sgd',
    name: 'Cash (SGD)',
    type: 'cash',
    currency: 'SGD',
    rewardRules: [],
    active: true,
    icon: 'banknote',
    color: '#22c55e',
  },
  {
    id: '1-ntd',
    name: 'Cash (NTD)',
    type: 'cash',
    currency: 'NTD',
    rewardRules: [],
    active: true,
    icon: 'banknote',
    color: '#22c55e',
  },
  {
    id: '1-cad',
    name: 'Cash (CAD)',
    type: 'cash',
    currency: 'CAD',
    rewardRules: [],
    active: true,
    icon: 'banknote',
    color: '#22c55e',
  },
  {
    id: '1-vnd',
    name: 'Cash (VND)',
    type: 'cash',
    currency: 'VND',
    rewardRules: [],
    active: true,
    icon: 'banknote',
    color: '#22c55e',
  },
  {
    id: '1-thb',
    name: 'Cash (THB)',
    type: 'cash',
    currency: 'THB',
    rewardRules: [],
    active: true,
    icon: 'banknote',
    color: '#22c55e',
  },
  // Credit cards
  {
    id: '2',
    name: 'Blue Cash Preferred',
    type: 'credit_card',
    currency: 'USD',
    issuer: 'American Express',
    lastFourDigits: '1234',
    statementStartDay: 15,
    isMonthlyStatement: true,
    active: true,
    icon: 'credit-card',
    color: '#3b82f6',
    rewardRules: [
      {
        id: '2-1',
        name: 'Grocery Bonus',
        description: '6% back at U.S. supermarkets',
        type: 'mcc',
        condition: '5411',
        pointsMultiplier: 6,
        maxSpend: 6000,
      },
      {
        id: '2-2',
        name: 'Streaming Bonus',
        description: '6% back on select U.S. streaming',
        type: 'merchant',
        condition: ['Netflix', 'Spotify', 'Disney', 'Hulu', 'HBO'],
        pointsMultiplier: 6,
      },
      {
        id: '2-3',
        name: 'Gas Bonus',
        description: '3% back at U.S. gas stations',
        type: 'mcc',
        condition: '5541',
        pointsMultiplier: 3,
      },
    ],
  },
  {
    id: '3',
    name: 'Chase Sapphire Reserve',
    type: 'credit_card',
    currency: 'USD',
    issuer: 'Chase',
    lastFourDigits: '5678',
    statementStartDay: 1,
    isMonthlyStatement: false,
    active: true,
    icon: 'credit-card',
    color: '#6366f1',
    rewardRules: [
      {
        id: '3-1',
        name: 'Travel Bonus',
        description: '3x points on travel',
        type: 'mcc',
        condition: '3000',
        pointsMultiplier: 3,
      },
      {
        id: '3-2',
        name: 'Dining Bonus',
        description: '3x points on dining',
        type: 'mcc',
        condition: '5812',
        pointsMultiplier: 3,
      },
    ],
  },
  {
    id: '4',
    name: 'Preferred Visa Platinum',
    type: 'credit_card',
    currency: 'SGD',
    issuer: 'UOB',
    lastFourDigits: '9012',
    statementStartDay: 1,
    isMonthlyStatement: false,
    active: true,
    icon: 'credit-card',
    color: '#1e3a8a',
    rewardRules: [], // Special handling in rewardPoints.ts
  },
  {
    id: '5',
    name: 'Visa Signature',
    type: 'credit_card',
    currency: 'SGD',
    issuer: 'UOB',
    lastFourDigits: '3456',
    statementStartDay: 1,
    isMonthlyStatement: true,
    active: true,
    icon: 'credit-card',
    color: '#7e22ce',
    rewardRules: [], // Special handling in rewardPoints.ts
    conversionRate: {
      USD: 1.35,
      EUR: 1.47,
      GBP: 1.73,
      SGD: 1,
      JPY: 0.0091,
      AUD: 0.89,
      CAD: 0.99,
      CNY: 0.19,
      INR: 0.016,
      NTD: 0.042,
      VND: 0.000054,
      IDR: 0.000086,
      THB: 0.038,
      MYR: 0.31
    }
  },
  {
    id: '6',
    name: 'Rewards Visa Signature',
    type: 'credit_card',
    currency: 'SGD',
    issuer: 'Citibank',
    lastFourDigits: '7890',
    statementStartDay: 1,
    isMonthlyStatement: true,
    active: true,
    icon: 'credit-card',
    color: '#0891b2',
    rewardRules: [], // Special handling in rewardPoints.ts
    conversionRate: {
      USD: 1.35,
      EUR: 1.47,
      GBP: 1.73,
      SGD: 1,
      JPY: 0.0091,
      AUD: 0.89,
      CAD: 0.99,
      CNY: 0.19,
      INR: 0.016,
      NTD: 0.042,
      VND: 0.000054,
      IDR: 0.000086,
      THB: 0.038,
      MYR: 0.31
    }
  },
];

// Helper function to find cash payment method for a specific currency
export const findCashPaymentMethodForCurrency = (currency: string): PaymentMethod | undefined => {
  return defaultPaymentMethods.find(method => 
    method.type === 'cash' && method.currency === currency
  );
};

