-- Expand recurring_income.frequency to include 'one_off' for bonuses,
-- refunds, and other single-shot income events that must NOT virtualize
-- into recurring occurrences.
--
-- The old CHECK constraint on the column allowed only ('biweekly',
-- 'monthly'). Drop it, replace with the new three-value set. No data
-- migration needed since existing rows already satisfy the new predicate.

DO $$
DECLARE
  cons_name text;
BEGIN
  -- Find the existing frequency CHECK constraint by matching its clause
  -- (name is auto-generated by Postgres and unstable across environments).
  SELECT conname INTO cons_name
  FROM pg_constraint
  WHERE conrelid = 'public.recurring_income'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%frequency%';

  IF cons_name IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.recurring_income DROP CONSTRAINT %I',
      cons_name
    );
  END IF;
END
$$;

ALTER TABLE public.recurring_income
  ADD CONSTRAINT recurring_income_frequency_check
  CHECK (frequency IN ('biweekly', 'monthly', 'one_off'));
