
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnaohzlumveyjkxctsft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuYW9oemx1bXZleWpreGN0c2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MzQxODMsImV4cCI6MjA1ODMxMDE4M30.rJhVIke_Zb123pOpDLfPgYNQT9G3qbdu4H_YqpChqYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Flag to indicate we should use local storage by default
export const USE_LOCAL_STORAGE_DEFAULT = false;
